import {mkdirSync,writeFileSync,copyFileSync,cpSync} from 'node:fs';
const origin='https://www.up-informatica.ch';
mkdirSync('assets/vendor',{recursive:true});
copyFileSync('node_modules/gsap/dist/gsap.min.js','assets/vendor/gsap.min.js');
copyFileSync('node_modules/gsap/dist/ScrollTrigger.min.js','assets/vendor/ScrollTrigger.min.js');
copyFileSync('node_modules/@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2','assets/vendor/manrope.woff2');
copyFileSync('node_modules/@fontsource-variable/manrope/LICENSE','assets/vendor/manrope-LICENSE.txt');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const arrow='<span aria-hidden="true">↗</span>';
const services=[
{slug:'assistenza-computer-domicilio-ticino',label:'Per la tua casa',title:'Il computer fa i capricci? Ci penso io.',short:'PC, Mac e dispositivi',desc:'Computer lenti, stampanti bloccate e nuovi dispositivi da configurare. Un aiuto concreto, direttamente a casa tua.',meta:'Assistenza PC e Mac a domicilio in Ticino. Configurazione, rimozione virus, backup e supporto per i tuoi dispositivi. Contatta Stefano.',items:[['PC e Mac','Analisi dei rallentamenti, problemi di avvio, aggiornamenti e installazione dei programmi che ti servono.'],['Stampanti e nuovi dispositivi','Collegamento della stampante, configurazione del nuovo computer e trasferimento dei tuoi documenti.'],['Sicurezza e backup','Rimozione di software indesiderato, impostazione delle copie di sicurezza e consigli per riconoscere messaggi sospetti.'],['Un aiuto per imparare','Ti accompagno nell’uso quotidiano di computer, email e servizi digitali, con spiegazioni semplici e al tuo ritmo.']],example:'Hai comprato un computer nuovo? Possiamo configurarlo, trasferire i file disponibili e collegarlo alla stampante e alla rete di casa.',faq:[['Devo portare il computer da qualche parte?','No: il servizio è a domicilio, su appuntamento. Se il problema richiede una lavorazione diversa, ne parliamo dopo la verifica.'],['Puoi recuperare i miei file?','Dipende dallo stato del dispositivo e dalle copie disponibili. Prima valuto la situazione: il recupero dei dati non può essere garantito.']]},
{slug:'assistenza-informatica-aziende-ticino',label:'Per la tua azienda',title:'Il lavoro continua. La tecnologia lo segue.',short:'Assistenza per aziende',desc:'Postazioni, email, reti e backup. Un riferimento per l’informatica della tua attività, direttamente nella tua sede.',meta:'Assistenza informatica per aziende in Ticino, direttamente nella tua sede. Computer, email, reti e backup per il lavoro quotidiano.',items:[['Postazioni di lavoro','Configurazione di PC e Mac, installazione software e risoluzione dei problemi che rallentano il lavoro.'],['Email e collaborazione','Configurazione della posta sui dispositivi e supporto agli strumenti usati per condividere documenti e lavorare insieme.'],['Reti e periferiche','Collegamento di computer, stampanti e dispositivi alla rete aziendale, con verifica dei problemi di connessione.'],['Protezione dei documenti','Organizzazione delle copie di sicurezza e verifica delle possibilità di ripristino in base alle esigenze dell’attività.']],example:'Una piccola attività apre una nuova postazione: preparo il computer, configuro email e stampante e verifico l’accesso agli strumenti di lavoro.',faq:[['Lavori anche con piccole attività e indipendenti?','Sì. Il supporto si adatta al contesto: dalla singola postazione alle esigenze di una piccola azienda.'],['Puoi intervenire senza interrompere il lavoro?','Concordiamo l’intervento e gli eventuali tempi di fermo prima di procedere. Le modalità dipendono dal problema e dai sistemi coinvolti.']]},
{slug:'wifi-reti-backup-ticino',label:'Tutto connesso',title:'Una connessione che arriva dove serve.',short:'Wi-Fi, reti e backup',desc:'Wi-Fi che non prende, dispositivi che non comunicano e file da proteggere. Mettiamo ordine, sul posto.',meta:'Configurazione Wi-Fi, reti e backup a domicilio e in azienda in Ticino. Verifica della copertura, stampanti e protezione dei documenti.',items:[['Wi-Fi di casa','Verifica della copertura, posizionamento del router e valutazione delle soluzioni adatte agli spazi.'],['Reti per il lavoro','Configurazione e verifica dei collegamenti tra postazioni, stampanti e dispositivi condivisi.'],['Copie di sicurezza','Scelta e configurazione di una soluzione di backup in base ai dati, ai dispositivi e alle tue esigenze.'],['Problemi di connessione','Controllo della rete locale per distinguere i problemi dei dispositivi da quelli che richiedono il supporto del tuo operatore.']],example:'Il Wi-Fi funziona in soggiorno ma non nello studio? Verifico la situazione sul posto e ti spiego le opzioni prima di proporre nuovi apparecchi.',faq:[['Devo comprare subito un nuovo router?','Non necessariamente. Prima controlliamo la configurazione e la copertura esistente; eventuali acquisti vengono concordati.'],['Un backup è uguale a sincronizzare i file?','Sono funzioni diverse: una cancellazione può propagarsi anche ai dispositivi sincronizzati. Valutiamo copie e versioni recuperabili in base al servizio utilizzato.']]},
{slug:'software-automazioni-ia-ticino',label:'Un passo avanti',title:'Meno lavoro ripetitivo. Più spazio alle idee.',short:'Software, automazioni e IA',desc:'Siti, applicazioni e strumenti su misura per rendere più semplici le attività di ogni giorno.',meta:'Sviluppo software, siti web, automazioni e soluzioni di intelligenza artificiale per le aziende del Ticino. Progetti su misura, obiettivi concreti.',items:[['Siti e applicazioni web','Progetti pensati per presentare i tuoi servizi o gestire un’attività specifica, con un’interfaccia chiara.'],['Software su misura','Strumenti per organizzare richieste, informazioni e flussi di lavoro quando le soluzioni standard non bastano.'],['Automazioni pratiche','Collegamento di passaggi ripetitivi: ad esempio raccogliere una richiesta e preparare le informazioni per chi deve gestirla.'],['Intelligenza artificiale','Valutazione di strumenti per assistere nella ricerca di informazioni, nelle bozze e nelle attività ripetitive, con verifiche umane dove necessarie.']],example:'Copi le stesse informazioni da un modulo a un foglio di lavoro? Partiamo da quel passaggio e valutiamo come automatizzarlo, senza complicare il resto.',faq:[['Devo sapere già quale software mi serve?','No. Partiamo dal problema, da come lavori oggi e dal risultato che vuoi ottenere.'],['L’intelligenza artificiale serve a ogni azienda?','No. La propongo quando offre un vantaggio concreto. A volte bastano una migliore organizzazione o una semplice automazione.']]}
];
const brand='<a class="brand" href="/" aria-label="UP! informatica, home"><span class="brand-mark">up<span>!</span></span><span class="brand-name">informatica<span>Stefano Vananti</span></span></a>';
function header(){return '<a class="skip" href="#main">Vai al contenuto</a><header><div class="wrap nav">'+brand+'<button class="menu-toggle" aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Navigazione principale"><a href="/#services">Servizi</a><a href="/assistenza-domicilio-ticino.html">Il territorio</a><a href="/#about">Chi sono</a><a class="nav-contact" href="/#contact">Parliamone '+arrow+'</a></nav></div></header>'}
function footer(){return '<footer><div class="wrap footer-top">'+brand+'<p>La tecnologia, dalla tua parte.<br>A casa tua. Nella tua azienda.</p><a href="tel:+41768057376">076 805 73 76 '+arrow+'</a></div><div class="wrap footer-bottom"><span>© '+new Date().getFullYear()+' UP! informatica di Stefano Vananti · Ticino, Svizzera</span><div><a href="/privacy-policy.html">Privacy</a><a href="/cookie-policy.html">Cookie</a><a href="/#contact">Contatti</a></div></div></footer>'}
function faq(rows){return '<div class="faq-list">'+rows.map(([q,a])=>'<details><summary>'+q+'<span aria-hidden="true">+</span></summary><p>'+a+'</p></details>').join('')+'</div>'}
function cta(){return '<section class="cta wrap"><p class="eyebrow">Partiamo da quello che ti serve</p><h2>Un problema da risolvere?<br>Un’idea da realizzare?</h2><a class="button dark" href="/#contact">Parliamone '+arrow+'</a></section>'}
const organization={'@type':'Organization','@id':origin+'/#organization',name:'UP! informatica',url:origin+'/',telephone:'+41768057376',email:'stefanovananti@icloud.com',founder:{'@type':'Person',name:'Stefano Vananti'},areaServed:{'@type':'AdministrativeArea',name:'Ticino, Svizzera'}};
function page(file,title,description,body,{schema=[],noindex=false}={}){
 const url=origin+(file==='index.html'?'/':'/'+file);
 const graph=[organization,{'@type':'WebPage','@id':url,name:title,url,description,inLanguage:'it-CH',isPartOf:{'@id':origin+'/#website'}},...schema];
 const html='<!doctype html>\n<html lang="it-CH"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(description)+'"><meta name="robots" content="'+(noindex?'noindex,follow':'index,follow')+'"><link rel="canonical" href="'+url+'"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/vendor/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/style.css"><meta name="theme-color" content="#182c29"><meta property="og:type" content="website"><meta property="og:locale" content="it_CH"><meta property="og:site_name" content="UP! informatica"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+url+'"><meta property="og:image" content="'+origin+'/favicon.svg"><script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@graph':graph})+'</script><script defer src="/assets/vendor/gsap.min.js"></script><script defer src="/assets/vendor/ScrollTrigger.min.js"></script><script defer src="/script.js"></script></head><body>'+header()+'<main id="main">'+body+'</main>'+footer()+'</body></html>\n';
 writeFileSync(file,html);
}
const contact='<section id="contact" class="contact-section"><div class="wrap contact-grid"><div><p class="eyebrow">Facciamo il primo passo</p><h2>Dimmi cosa<br>ti serve.</h2><p>Un problema al computer o un progetto da sviluppare: raccontami la situazione e il comune in cui ti trovi.</p><a class="contact-phone" href="tel:+41768057376">076 805 73 76 '+arrow+'</a><div class="contact-links"><a href="https://wa.me/41768057376">Scrivimi su WhatsApp '+arrow+'</a><a href="mailto:stefanovananti@icloud.com">stefanovananti@icloud.com</a></div><p class="small">Interventi su appuntamento, a domicilio e in azienda.<br>Modalità, tempi e costi vengono concordati prima dell’intervento.</p></div><form id="contact-form" action="https://formspree.io/f/mgvyvvjw" method="POST"><div class="field-pair"><label>Il tuo nome<input name="name" autocomplete="name" required maxlength="100" placeholder="Nome e cognome"></label><label>La tua email<input type="email" name="email" autocomplete="email" required maxlength="254" placeholder="nome@esempio.ch"></label></div><div class="field-pair"><label>Comune<input name="comune" autocomplete="address-level2" required maxlength="100" placeholder="Dove ti serve una mano?"></label><label>Di cosa hai bisogno?<select name="subject" required><option value="">Scegli un servizio</option>Assistenza PC e Mac</option><option>Assistenza aziendale</option><option>Wi-Fi, reti e backup</option><option>Software, automazioni e IA</option><option>Consulenza e formazione</option></select></label></div><label>Raccontami la situazione<textarea name="message" required minlength="10" maxlength="5000" rows="4" placeholder="Qual è il problema o il progetto?"></textarea></label><div class="honeypot" aria-hidden="true"><label>Lascia vuoto<input name="_gotcha" tabindex="-1" autocomplete="off"></label></div><p class="small">I dati vengono inviati tramite Formspree per rispondere alla tua richiesta. Leggi l’<a href="/privacy-policy.html">informativa privacy</a>. Non inserire password o dati sensibili.</p><button class="button lime" type="submit">Invia la richiesta '+arrow+'</button><p id="form-messages" role="status" aria-live="polite"></p></form></div></section>';
page('index.html','Assistenza informatica a domicilio in Ticino | UP! informatica','Assistenza PC e Mac a domicilio e in azienda in tutto il Ticino. Wi-Fi, backup, software e automazioni: un aiuto pratico con Stefano Vananti.',
 '<section class="hero wrap" id="hero"><div class="hero-top"><p class="eyebrow"><span class="cross" aria-hidden="true">✳</span> Informatica a domicilio · Tutto il Ticino</p><span class="hero-note">Per le persone.<br>Per le imprese.</span></div><h1>La tecnologia,<br><span>dalla tua parte.</span></h1><div class="hero-bottom"><p>Il PC che si blocca. Il Wi-Fi che non arriva.<br>L’idea che vuoi far crescere.<br><strong>Vengo da te. Troviamo la soluzione.</strong></p><div class="hero-actions"><a class="button dark" href="#contact">Chiedi una mano '+arrow+'</a><a class="text-link" href="#services">Scopri cosa posso fare <span aria-hidden="true">↓</span></a></div></div><div class="hero-photo"><img src="/assets/images/home-office.jpg" width="1536" height="1024" alt="Un computer su una scrivania luminosa, con vista sul paesaggio ticinese" fetchpriority="high"><div class="photo-caption"><span>Il tuo spazio.<br>La mia prossima destinazione.</span><span class="caption-label">A casa tua<br>o nella tua azienda '+arrow+'</span></div></div></section>'+
 '<div class="service-strip" aria-label="Servizi principali"><div class="wrap"><span>PC & Mac</span><b aria-hidden="true">✳</b><span>Wi-Fi & reti</span><b aria-hidden="true">✳</b><span>Software & IA</span><b aria-hidden="true">✳</b><span>Persone, prima di tutto</span></div></div>'+
 '<section id="services" class="section wrap"><div class="section-heading"><p class="eyebrow">01 / Come posso aiutarti</p><h2>Problemi quotidiani.<br>Possibilità nuove.</h2><p>Dalla stampante che non collabora al software che manca alla tua attività. Partiamo da un’esigenza concreta.</p></div><div class="service-list">'+services.map((s,i)=>'<a class="service-row" href="/'+s.slug+'.html"><span class="service-number">0'+(i+1)+'</span><div><span class="eyebrow">'+s.label+'</span><h3>'+s.short+'</h3></div><p>'+s.desc+'</p><span class="round-arrow" aria-hidden="true">↗</span></a>').join('')+'</div></section>'+
 '<section class="approach"><div class="wrap approach-grid"><div><p class="eyebrow">Semplice, dall’inizio alla fine</p><h2>Tu mi racconti.<br>Io ti ascolto.<br><em>Poi si risolve.</em></h2></div><ol><li><span>01</span><div><h3>Parliamo del problema</h3><p>Mi dici cosa non funziona o cosa vorresti migliorare. Anche senza conoscere i termini tecnici.</p></div></li><li><span>02</span><div><h3>Concordiamo l’intervento</h3><p>Valutiamo insieme modalità, appuntamento e costi, comprese le eventuali trasferte.</p></div></li><li><span>03</span><div><h3>Vengo da te</h3><p>Intervengo a casa tua o nella tua azienda e ti spiego quello che faccio, con parole chiare.</p></div></li></ol></div></section>'+
 '<section class="section wrap territory"><div><p class="eyebrow">02 / Vicino, dove conta</p><h2>Un Ticino intero.<br>Un solo contatto.</h2><p>Vivo a Biasca e mi sposto nel Sopraceneri. Con un appoggio a Lugano, organizzo gli interventi anche nel Sottoceneri.</p><p>Non devi raggiungere un negozio: <strong>il servizio arriva a casa tua o nella tua azienda</strong>, su appuntamento.</p><a class="text-link" href="/assistenza-domicilio-ticino.html">Scopri le zone servite '+arrow+'</a></div><div class="area-board"><div class="area-title"><span>CH — TI</span><span>Servizio a domicilio</span></div><div class="area"><span class="area-pin" aria-hidden="true">01</span><div><h3>Sopraceneri</h3><p>Biasca · Bellinzona · Locarno<br>Riviera · Leventina · Blenio · Vallemaggia</p></div></div><div class="area"><span class="area-pin" aria-hidden="true">02</span><div><h3>Sottoceneri</h3><p>Lugano · Mendrisio · Chiasso<br>Luganese · Malcantone · Mendrisiotto</p></div></div><p class="small">Indica il tuo comune quando mi contatti: concordiamo disponibilità e trasferta.</p></div></section>'+
 '<section id="about" class="about-section"><div class="wrap about-grid"><div class="about-signature"><span class="eyebrow">03 / Piacere, Stefano</span><span class="big-up" aria-hidden="true">up!</span><span>Una persona.<br>Un riferimento.</span></div><div><h2>Dietro la tecnologia,<br>ci sono le persone.</h2><p>Sono Stefano Vananti, la persona dietro UP! informatica. Vivo a Biasca e aiuto privati e aziende del Ticino a usare meglio la tecnologia.</p><p>Mi piace risolvere i problemi pratici e sviluppare nuove soluzioni. Un computer che torna utile, una rete che funziona, un’attività ripetitiva che diventa più semplice.</p><p class="about-quote">“Prima capisco cosa ti serve.<br>Poi troviamo il modo di farlo.”</p></div></div></section>'+
 '<section class="section wrap faq-section"><div><p class="eyebrow">Prima di sentirci</p><h2>Qualche risposta,<br>senza tecnicismi.</h2></div>'+faq([['Vieni davvero a domicilio in tutto il Ticino?','Sì, organizzo interventi a casa e in azienda nel Sopraceneri e nel Sottoceneri. Indica il comune: concordiamo disponibilità, tempi e condizioni di trasferta.'],['Quanto costa un intervento?','Dipende dal problema, dal lavoro necessario e dalla trasferta. Prima di procedere concordiamo modalità e costi. Puoi contattarmi per descrivere la situazione.'],['Ti occupi sia di PC sia di Mac?','Sì. Offro assistenza per PC e Mac, configurazione dei dispositivi, software, reti e backup.'],['Ho una piccola azienda: puoi aiutarmi?','Certo. Possiamo partire da una singola esigenza, come la posta elettronica o una stampante, e valutare insieme le altre necessità.'],['Puoi aiutarmi con automazioni e intelligenza artificiale?','Sì. Partiamo da un’attività concreta per capire se un software, un’automazione o uno strumento di IA può semplificarla.']])+'</section>'+contact,
 {schema:[{'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'UP! informatica',inLanguage:'it-CH'}]});
for(const [i,s] of services.entries()) page(s.slug+'.html',s.short+' in Ticino | UP! informatica',s.meta,
 '<section class="wrap detail-hero"><a class="breadcrumb" href="/#services">Servizi / '+s.label+'</a><p class="eyebrow">0'+(i+1)+' / '+s.label+'</p><h1>'+s.title+'</h1><p class="lead">'+s.desc+'</p><a class="button dark" href="/#contact">Raccontami cosa ti serve '+arrow+'</a></section><section class="wrap detail-content"><div class="detail-intro"><p class="eyebrow">Cosa possiamo fare</p><h2>Un aiuto concreto.<br>Su misura per te.</h2><p>A domicilio e in azienda in tutto il Ticino, su appuntamento.</p></div><div class="detail-items">'+s.items.map(([a,b])=>'<article><h3>'+a+'</h3><p>'+b+'</p></article>').join('')+'</div></section><aside class="example wrap"><p class="eyebrow">Per esempio</p><p>'+s.example+'</p></aside><section class="wrap section faq-section"><h2>Prima di iniziare.</h2>'+faq(s.faq)+'</section>'+cta(),
 {schema:[{'@type':'Service',name:s.short,serviceType:s.short,provider:{'@id':origin+'/#organization'},areaServed:{'@type':'AdministrativeArea',name:'Ticino, Svizzera'},url:origin+'/'+s.slug+'.html'}]});
page('assistenza-domicilio-ticino.html','Assistenza a domicilio in tutto il Ticino | UP! informatica','Servizi informatici a domicilio nel Sopraceneri e Sottoceneri: Biasca, Bellinzona, Locarno, Lugano, Mendrisio e valli. Interventi su appuntamento.',
 '<section class="wrap detail-hero"><a class="breadcrumb" href="/">Home / Il territorio</a><p class="eyebrow">Da Biasca, in tutto il cantone</p><h1>L’informatica<br>viene da te.</h1><p class="lead">A casa o nella tua attività, nel Sopraceneri e nel Sottoceneri. Un unico contatto per organizzare l’intervento.</p></section><section class="wrap territory-detail"><article><span class="eyebrow">01 / Da Biasca</span><h2>Sopraceneri</h2><p>Vivo a Biasca: da qui organizzo gli interventi a Bellinzona, Locarno e nelle valli. Il servizio copre Riviera, Leventina, Blenio e Vallemaggia.</p><p>Computer, stampanti, reti e assistenza sul posto, sia per le abitazioni sia per le attività della zona.</p></article><article><span class="eyebrow">02 / Con appoggio a Lugano</span><h2>Sottoceneri</h2><p>Un appoggio a Lugano mi permette di organizzare gli appuntamenti nel Luganese, nel Malcantone e nel Mendrisiotto, fino a Mendrisio e Chiasso.</p><p>Il servizio si svolge presso il cliente. Non c’è uno sportello o un ufficio aperto al pubblico.</p></article></section><section class="wrap section faq-section"><h2>Organizziamo<br>la visita.</h2>'+faq([['Il mio comune non è nell’elenco. Posso contattarti?','Sì. Le località indicate sono esempi della copertura in Ticino. Scrivimi il tuo comune e la tua esigenza per verificare l’appuntamento.'],['Sono previsti costi di trasferta?','Le condizioni dipendono dalla località e dall’intervento. Le concordiamo prima dell’appuntamento.'],['Posso passare senza appuntamento?','Il servizio è a domicilio e in azienda: contattami per organizzare un intervento presso di te. Non ricevo clienti in un negozio.']])+'</section>'+cta());
page('privacy-policy.html','Informativa privacy | UP! informatica','Informazioni sui dati trattati dal sito UP! informatica e sulle richieste di contatto.',
 '<article class="wrap legal"><p class="eyebrow">Informazioni sul sito</p><h1>Privacy.</h1><p>Ultimo aggiornamento: 15 settembre 2026.</p><h2>Chi gestisce i dati</h2><p>UP! informatica di Stefano Vananti, Biasca, Svizzera. Per domande sul trattamento dei dati: <a href="mailto:stefanovananti@icloud.com">stefanovananti@icloud.com</a>, telefono <a href="tel:+41768057376">076 805 73 76</a>.</p><h2>Richieste di contatto</h2><p>Il modulo raccoglie nome, email, comune, servizio richiesto e messaggio. Queste informazioni servono a rispondere e organizzare l’eventuale intervento. Non inserire password, dati di pagamento o informazioni sensibili.</p><p>Il modulo invia i dati a Formspree, il servizio già utilizzato per ricevere le richieste. Formspree può trattare dati negli Stati Uniti. Consulta la <a href="https://formspree.io/legal/privacy-policy/">privacy di Formspree</a> per informazioni sul suo trattamento.</p><h2>Hosting e dati tecnici</h2><p>Il sito è ospitato su Vercel. Per fornire il servizio, il gestore dell’infrastruttura può trattare dati tecnici, come indirizzo IP e informazioni della richiesta, anche all’estero, inclusi gli Stati Uniti. Maggiori informazioni nella <a href="https://vercel.com/legal/privacy-policy">privacy di Vercel</a>.</p><h2>Cookie e servizi esterni</h2><p>Il codice di questo sito non imposta cookie di marketing o analisi e non include strumenti pubblicitari. Caratteri, immagini e librerie vengono serviti dal sito. I link a WhatsApp e ad altri siti aprono servizi esterni, ai quali si applicano le rispettive informative. Vedi anche la <a href="/cookie-policy.html">pagina cookie</a>.</p><h2>Conservazione e richieste sui dati</h2><p>Le informazioni delle richieste sono conservate per il tempo necessario a gestire il contatto e il rapporto con il cliente, tenendo conto degli obblighi applicabili. Puoi scrivere all’indirizzo indicato per chiedere informazioni, rettifica o cancellazione dei tuoi dati; eventuali obblighi di conservazione possono limitare la cancellazione.</p></article>');
page('cookie-policy.html','Cookie e servizi esterni | UP! informatica','Come il sito UP! informatica utilizza cookie, risorse locali e collegamenti a servizi esterni.',
 '<article class="wrap legal"><p class="eyebrow">Informazioni sul sito</p><h1>Cookie.</h1><p>Ultimo aggiornamento: 15 settembre 2026.</p><h2>Cosa utilizza questo sito</h2><p>Il codice del sito non imposta cookie di analisi o marketing, non salva preferenze nel browser e non carica pubblicità. Il menu, le animazioni e le domande frequenti funzionano senza cookie.</p><h2>Risorse e collegamenti</h2><p>Caratteri, immagini e librerie sono ospitati insieme al sito. Il modulo contatti comunica con Formspree solo al momento dell’invio. I collegamenti a WhatsApp e agli altri servizi esterni sono soggetti alle politiche dei rispettivi fornitori quando li apri.</p><h2>Informazioni sul trattamento</h2><p>Per i dati tecnici dell’hosting e quelli inviati tramite il modulo, consulta l’<a href="/privacy-policy.html">informativa privacy</a>. Puoi gestire i cookie e i dati dei siti dalle impostazioni del tuo browser.</p></article>');
page('404.html','Pagina non trovata | UP! informatica','La pagina richiesta non è disponibile. Torna ai servizi di UP! informatica.','<section class="wrap detail-hero"><p class="eyebrow">404 / Qui non c’è una pagina</p><h1>Ripartiamo<br>da casa.</h1><p class="lead">Puoi trovare i servizi e i contatti nella pagina principale.</p><a class="button dark" href="/">Torna alla home '+arrow+'</a></section>',{noindex:true});
const files=['index.html',...services.map(s=>s.slug+'.html'),'assistenza-domicilio-ticino.html','privacy-policy.html','cookie-policy.html'];
writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+files.map(f=>'<url><loc>'+origin+(f==='index.html'?'/':'/'+f)+'</loc></url>').join('')+'</urlset>\n');
writeFileSync('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+origin+'/sitemap.xml\n');
console.log('Built '+(files.length+1)+' HTML pages with local fonts and GSAP.');
mkdirSync('public',{recursive:true});
for(const file of [...files,'404.html','style.css','script.js','favicon.svg','robots.txt','sitemap.xml'])copyFileSync(file,'public/'+file);
cpSync('assets','public/assets',{recursive:true});
